In [ ]:
import torch
import numpy as np

In [ ]:
# Создайте случайный FloatTensor размера 3x4x5

In [ ]:
x = torch.randn(3, 4, 5)
x

tensor([[[-0.5636,  0.6674, -2.3822, -0.6340, -0.4562],
         [ 0.3917, -1.4364, -1.4312,  0.8380, -0.6750],
         [-1.0552,  0.8529, -1.5532,  0.6240,  0.5606],
         [ 0.1905, -0.4183,  0.1350,  1.1219, -1.0545]],

        [[-1.4060,  0.7498,  0.9165, -1.0740,  0.8780],
         [-2.3830, -1.8121, -2.9622, -0.6011,  0.7147],
         [-2.1057, -1.4655, -0.4296, -0.2848,  0.7124],
         [ 2.3791, -0.9891, -0.3595,  0.0925, -2.0130]],

        [[-0.9280,  1.5910, -0.3505,  1.9083,  2.0429],
         [-0.5655, -0.5118, -1.5474,  2.2626,  1.5349],
         [ 0.9573,  1.3339,  1.0019,  0.6972,  0.2836],
         [-0.5506, -1.4062,  1.2450, -0.0488, -0.0283]]])

In [ ]:
x.type()

'torch.FloatTensor'

In [ ]:
y = torch.FloatTensor(x)
y

tensor([[[-0.5636,  0.6674, -2.3822, -0.6340, -0.4562],
         [ 0.3917, -1.4364, -1.4312,  0.8380, -0.6750],
         [-1.0552,  0.8529, -1.5532,  0.6240,  0.5606],
         [ 0.1905, -0.4183,  0.1350,  1.1219, -1.0545]],

        [[-1.4060,  0.7498,  0.9165, -1.0740,  0.8780],
         [-2.3830, -1.8121, -2.9622, -0.6011,  0.7147],
         [-2.1057, -1.4655, -0.4296, -0.2848,  0.7124],
         [ 2.3791, -0.9891, -0.3595,  0.0925, -2.0130]],

        [[-0.9280,  1.5910, -0.3505,  1.9083,  2.0429],
         [-0.5655, -0.5118, -1.5474,  2.2626,  1.5349],
         [ 0.9573,  1.3339,  1.0019,  0.6972,  0.2836],
         [-0.5506, -1.4062,  1.2450, -0.0488, -0.0283]]])

In [ ]:
y.type()

'torch.FloatTensor'

In [ ]:
# Выведите его форму (shape)

In [ ]:
x.size()

torch.Size([3, 4, 5])

In [ ]:
x.numpy().shape

(3, 4, 5)

In [ ]:
# Приведите его к форме 6 X 10

In [ ]:
torch.reshape(x, (6, -1)).size()

torch.Size([6, 10])

In [ ]:
# Умножьте его на вектор [1, 4, 2, 2, 1] поэлементно

In [ ]:
y = torch.reshape(x, (6, 10))

In [ ]:
y 

tensor([[-0.5636,  0.6674, -2.3822, -0.6340, -0.4562,  0.3917, -1.4364, -1.4312,
          0.8380, -0.6750],
        [-1.0552,  0.8529, -1.5532,  0.6240,  0.5606,  0.1905, -0.4183,  0.1350,
          1.1219, -1.0545],
        [-1.4060,  0.7498,  0.9165, -1.0740,  0.8780, -2.3830, -1.8121, -2.9622,
         -0.6011,  0.7147],
        [-2.1057, -1.4655, -0.4296, -0.2848,  0.7124,  2.3791, -0.9891, -0.3595,
          0.0925, -2.0130],
        [-0.9280,  1.5910, -0.3505,  1.9083,  2.0429, -0.5655, -0.5118, -1.5474,
          2.2626,  1.5349],
        [ 0.9573,  1.3339,  1.0019,  0.6972,  0.2836, -0.5506, -1.4062,  1.2450,
         -0.0488, -0.0283]])

In [ ]:
z = torch.reshape(((torch.reshape(y, (-1, 5)) * torch.LongTensor([1, 4, 2, 2, 1]))), (6, 10))

In [ ]:
z

tensor([[-0.5636,  2.6695, -4.7644, -1.2681, -0.4562,  0.3917, -5.7455, -2.8624,
          1.6761, -0.6750],
        [-1.0552,  3.4114, -3.1064,  1.2479,  0.5606,  0.1905, -1.6731,  0.2701,
          2.2438, -1.0545],
        [-1.4060,  2.9994,  1.8330, -2.1481,  0.8780, -2.3830, -7.2484, -5.9245,
         -1.2022,  0.7147],
        [-2.1057, -5.8620, -0.8591, -0.5697,  0.7124,  2.3791, -3.9563, -0.7190,
          0.1849, -2.0130],
        [-0.9280,  6.3639, -0.7009,  3.8167,  2.0429, -0.5655, -2.0473, -3.0948,
          4.5251,  1.5349],
        [ 0.9573,  5.3355,  2.0038,  1.3945,  0.2836, -0.5506, -5.6249,  2.4901,
         -0.0976, -0.0283]])

In [ ]:
z.size()

torch.Size([6, 10])

In [ ]:
# Умножьте тензор матрично на себя, чтобы результат был размерности 6x6

In [ ]:
v = z @ z.T

In [ ]:
v.size()

torch.Size([6, 6])

In [ ]:
# Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)

In [ ]:
from torch.autograd import Variable

In [ ]:
x = Variable(torch.ones(3), requires_grad = True)

In [ ]:
z = 5 * x

In [ ]:
t = 5 / x

In [ ]:
y = x**3 + z - 75 * t

In [ ]:
y.backward(torch.tensor([1, 0.5, 2]))

In [ ]:
print(x.grad)

tensor([383.0000, 191.5000, 766.0000])


In [ ]:
# Создайте единичный тензор размера 5x6

In [ ]:
x = torch.ones((5, 6))
x

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [ ]:
# Переведите его в формат numpy

In [ ]:
y = x.numpy()
y

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)

In [ ]:
# Давайте теперь пооптимизируем: возьмите функцию y = x**w1 - 2 * x**2 + 5
# Посчитайте 